import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/quiz/Quiz.module.css'
import { useRouter } from 'next/router'
import quizdata from '@/data/quiz.json'
import buttondata from '@/data/otherbutton.json'
import Logo from '@/components/Logo'
import MenuBurger from '@/components/MenuBurger'
import ProgressBar from '@/components/ProgressBar'
import { useState } from 'react'
import Buttons from '@/components/Buttons/QuizButton'
import OtherButton from '@/components/Buttons/OtherButton'
import NavBar from '@/components/NavBar'


export default function Quiz1() {
    const [question, setQuestion] = useState([...quizdata])
    const [button, setButton] = useState([...buttondata])

    const Quiz = () => {
        const [score, setScore] = useState(0);

        const updateScore = (points) => {
            setScore(points);
        };


        const questions = [
            {
                questionNumber: 'One',
                options: [
                    { option: 'Repurpose them', point: 2 },
                    { option: 'Throw them out', point: 0 },
                    { option: 'Donate them', point: 1 },
                ],
            },
            // add more questions here
        ];

        return (
            <div>
                {questions.map((question, index) => (
                    <div key={index}>
                        <h2>{question.questionNumber}</h2>
                        {question.options.map((option, index) => (
                            <Buttons
                                key={index}
                                option={option}
                                buttons="3"
                                updateScore={updateScore}
                            />
                        ))}
                    </div>
                ))}
                <p>Your score: {score}</p>
            </div>
        );
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.header}>
                    <NavBar />
                </div>

                <ProgressBar percentage={25} />

                <div className={styles.quiz_container}>
                    <Quiz />
                </div>

                <div className={styles.back_and_next}>
                    {button.map((info, index) => {
                        if (info.buttons.toLowerCase() === 'quiz') {
                            return (
                                <OtherButton
                                    key={index}
                                    back={info.back}
                                    next={info.next}
                                    type="quiz"
                                    hrefBack="none"
                                    hrefNext="/quiz/quiz2"
                                />
                            );
                        }
                    })}
                </div>

            </main >
        </>
    )
}
