import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/quiz/Quiz.module.css'
import { useRouter } from 'next/router'
import quizdata from '@/data/quiz.json'
import buttondata from '@/data/otherbutton.json'
import Logo from '@/components/Logo'
import MenuBurger from '@/components/MenuBurger'
import ProgressBar from '@/components/ProgressBar'
import { useState } from 'react'
import Buttons from '@/components/Buttons/QuizButton'
import OtherButton from '@/components/Buttons/OtherButton'
import NavBar from '@/components/NavBar'


export default function Quiz2() {

    const [question, setQuestion] = useState([...quizdata])
    const [button, setButton] = useState([...buttondata])
    const [score, setScore] = useState(0);

    const updateScore = (points) => {
        setScore(points);
    };
    const Quiz = () => {
        const [score, setScore] = useState(0);

        const updateScore = (points) => {
            setScore(score + points);
        }
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.header}>
                    <NavBar />
                </div>

                <ProgressBar percentage={50} />
                <div>
                    <div className={styles.quiz_container}>
                        {question &&
                            question.map((info, index) => {
                                if (info && info.questionID && info.questionID.toLowerCase() === "two") {
                                    return (
                                        <div key={index}>
                                            <h3>{info.question}</h3>
                                            {info.options.map((option, optionIndex) => (
                                                <Buttons key={optionIndex} option={option} buttons="3" updateScore={updateScore} />
                                            ))}
                                        </div>
                                    );
                                }
                            })}
                    </div>
                    <p>Score: {score}</p>
                </div>




                <div className={styles.back_and_next}>
                    {button.map((info, index) => {
                        if (info.buttons.toLowerCase() === 'quiz') {
                            return (
                                <OtherButton
                                    key={index}
                                    back={info.back}
                                    next={info.next}
                                    type="quiz"
                                    hrefBack="/quiz/quiz1"
                                    hrefNext="/quiz/quiz3"
                                />
                            );
                        }
                    })}
                </div>


            </main >
        </>
    )
}
