import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/quiz/Quiz.module.css'
import { useRouter } from 'next/router'
import quizdata from '@/data/quiz.json'
import buttondata from '@/data/otherbutton.json'
import Logo from '@/components/Logo'
import MenuBurger from '@/components/MenuBurger'
import ProgressBar from '@/components/ProgressBar'
import { useState, useEffect } from 'react'
import Buttons from '@/components/Buttons/QuizButton'
import OtherButton from '@/components/Buttons/OtherButton'

export default function Quiz() {
    const [questionIndex, setQuestionIndex] = useState(1);
    const [question, setQuestion] = useState([...quizdata]);
    const [button, setButton] = useState([...buttondata]);
    const [score, setScore] = useState(0);
    const [nextClicked, setNextClicked] = useState(false);
    const [selectedOptions, setSelectedOptions] = useState({});

    const updateScore = (questionID, optionIndex, points) => {
        const currentOptionIndex = selectedOptions[questionID];
        if (currentOptionIndex !== undefined && currentOptionIndex === optionIndex) {
            return;
        }
        const selectedOptionPoints = question.find(q => q.questionID === questionID).options[optionIndex].point;
        const currentOptionPoints = currentOptionIndex !== undefined ? question.find(q => q.questionID === questionID).options[currentOptionIndex].point : 0;
        setScore(score - currentOptionPoints + selectedOptionPoints);
        setSelectedOptions({
            ...selectedOptions,
            [questionID]: optionIndex
        });
    };

    useEffect(() => {
        setQuestion([...quizdata].slice(questionIndex - 1, questionIndex));
    }, [questionIndex]);

    const handleNextQuestion = () => {
        const activeButton = document.querySelector(`.${styles.buttons} button.${styles.active}`);
        if (activeButton) {
            activeButton.classList.remove(styles.active);
        }
        setQuestionIndex(questionIndex + 1);
    };

    const handleBackQuestion = () => {
        setQuestionIndex(questionIndex - 1);
        const buttons = document.querySelectorAll(`.${styles.buttons} button`);
        buttons.forEach((button) => {
            button.classList.remove(styles.active);
        });
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.header}>
                    <Logo page="intro" />
                    <MenuBurger />
                </div>
                <ProgressBar questionIndex={questionIndex} totalQuestions={quizdata.length} />
                <div>
                    <div className={styles.quiz_container}>
                        {question && question.map((info, index) => (
                            <div key={index}>
                                <h3>{info.question}</h3>
                                {info.options.map((option, optionIndex) => (
                                    <Buttons
                                        key={`${questionIndex}-${optionIndex}`}
                                        option={option}
                                        buttons="3"
                                        selected={selectedOptions[info.questionID] === optionIndex}
                                        updateScore={(points) => updateScore(info.questionID, optionIndex, points)}
                                        disableButtons={nextClicked}
                                    />

                                ))}
                            </div>
                        ))}
                    </div>
                    <p>Score: {score}</p>
                </div>
                <div className={styles.back_and_next}>
                    {button.map((info, index) => {
                        if (info.buttons.toLowerCase() === 'quiz') {
                            return (
                                <OtherButton
                                    key={index}
                                    back={info.back}
                                    next={info.next}
                                    type="quiz"
                                    onNext={handleNextQuestion}
                                    onBack={handleBackQuestion}
                                />
                            );
                        }
                    })}
                </div>
            </main>
        </>
    );
}
