import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/quiz/Quiz1.module.css'
import { useRouter } from 'next/router'
import quizdata from '@/data/quiz.json'
import buttondata from '@/data/otherbutton.json'
import Logo from '@/components/Logo'
import MenuBurger from '@/components/MenuBurger'
import ProgressBar from '@/components/ProgressBar'
import { useState } from 'react'
import Buttons from '@/components/Buttons/QuizButton'
import OtherButton from '@/components/Buttons/OtherButton'


export default function Quiz2() {

    const [question, setQuestion] = useState([...quizdata])
    const [button, setButton] = useState([...buttondata])

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.header}>
                    <Logo page="intro" />
                    <MenuBurger />
                </div>

                <ProgressBar percentage={50} />

                <div className={styles.quiz_container}>
                    <h2 className={styles.question}>2. Where do you shop frequently? </h2>
                    {
                        question && question.map((info, index) => {
                            if (info.questionNumber.toLowerCase() === "two") {
                                return (
                                    <>
                                        <Buttons key={index} option={info.option} buttons="3" />
                                    </>
                                )
                            }
                        })
                    }
                </div>

                <div className={styles.back_and_next}>
                    {button.map((info, index) => {
                        if (info.buttons.toLowerCase() === 'quiz') {
                            return (
                                <OtherButton
                                    key={index}
                                    back={info.back}
                                    next={info.next}
                                    type="quiz"
                                />
                            );
                        }
                    })}
                </div>

            </main >
        </>
    )
}
