import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/quiz/Quiz1.module.css'
import { useRouter } from 'next/router'
import data from '@/data/quiz.json'
import Logo from '@/components/Logo'
import MenuBurger from '@/components/MenuBurger'
import ProgressBar from '@/components/ProgressBar'
import { useState } from 'react'
import Buttons from '@/components/Buttons/QuizButton'


export default function Quiz3() {
    console.log(data);
    const [question, setQuestion] = useState([...data])

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.header}>
                    <Logo page="intro" />
                    <MenuBurger />
                </div>

                <ProgressBar percentage={75} />

                <div className={styles.quiz_container}>
                    <h2 className={styles.question}>3. Do you use reusable products? Ex. straws, cups, bags</h2>
                    {
                        question && question.map((info, index) => {
                            if (info.questionNumber.toLowerCase() === "three") {
                                return (
                                    <>
                                        <Buttons key={index} option={info.option} buttons="2" />
                                    </>

                                )
                            }
                        })
                    }
                </div>

            </main >
        </>
    )
}
