import Head from 'next/head'
import styles from '@/components/MenuBurger/MenuBurger.module.css'

export default function MenuBurger() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.menu_burger}>
                    <div className={styles.burger_line}></div>
                    <div className={styles.burger_line}></div>
                    <div className={styles.burger_line}></div>
                </div>

            </main >
        </>
    )
}
