import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/QuizIntro.module.css'
import { useRouter } from 'next/router'
import Logo from '@/components/Logo'
import NavBar from '@/components/NavBar'


export default function Quiz() {
    const router = useRouter()
    return (
        <>
            <Head>
                <title>Recyclonaut</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.svg" />
            </Head>
            <main className={styles.main}>
                <div className={styles.container}>
                    <div className={styles.header}>
                        <NavBar page='quiz' />
                    </div>
                    <h2 className={styles.heading}>Team Assessment</h2>
                    <div className={styles.intro}>
                        <p>
                            Welcome aboard! We have created a brief quiz to help us assign you to a team that aligns with your answers.<br /><br />
                            This will enable us to provide you with a set of tasks that can be easily integrated into your daily routine. <br /><br />
                            Remember, small changes can lead to massive results.
                            Let's work together to achieve remarkable outcomes!</p>
                    </div>
                    <Image />
                    <div className={styles.buttons}>
                        <button className={styles.button} onClick={() => router.push('./quiz/quiz')}>
                            Find Team
                        </button>
                        <button className={styles.button} onClick={() => router.push('/')}>
                            Return Home
                        </button>
                    </div>
                    <Image src={'/story/journey.png'} width={414} height={250}/>
                </div>
            </main>
        </>
    )
}
